/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthAccountRouteImport } from './routes/_auth/_account'
import { Route as AuthCheckoutRouteImport } from './routes/_auth/checkout'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as AuthAccountActivityRouteImport } from './routes/_auth/_account/activity'
import { Route as AuthAccountDownloadsRouteImport } from './routes/_auth/_account/downloads'
import { Route as AuthAccountOffersRouteImport } from './routes/_auth/_account/offers'
import { Route as AuthAccountProfileRouteImport } from './routes/_auth/_account/profile'
import { Route as AuthAccountSupportRouteImport } from './routes/_auth/_account/support'
import { Route as AuthAccountWalletsRouteImport } from './routes/_auth/_account/wallets'
import { Route as AuthAccountWatchlistRouteImport } from './routes/_auth/_account/watchlist'
import { Route as AuthOrdersOrderIdRouteImport } from './routes/_auth/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckoutRoute = AuthCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountActivityRoute = AuthAccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountDownloadsRoute = AuthAccountDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountOffersRoute = AuthAccountOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountProfileRoute = AuthAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountSupportRoute = AuthAccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountWalletsRoute = AuthAccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountWatchlistRoute = AuthAccountWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthOrdersOrderIdRoute = AuthOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthCheckoutRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/learn/': typeof LearnIndexRoute
  '/activity': typeof AuthAccountActivityRoute
  '/downloads': typeof AuthAccountDownloadsRoute
  '/offers': typeof AuthAccountOffersRoute
  '/profile': typeof AuthAccountProfileRoute
  '/support': typeof AuthAccountSupportRoute
  '/wallets': typeof AuthAccountWalletsRoute
  '/watchlist': typeof AuthAccountWatchlistRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthCheckoutRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/learn': typeof LearnIndexRoute
  '/activity': typeof AuthAccountActivityRoute
  '/downloads': typeof AuthAccountDownloadsRoute
  '/offers': typeof AuthAccountOffersRoute
  '/profile': typeof AuthAccountProfileRoute
  '/support': typeof AuthAccountSupportRoute
  '/wallets': typeof AuthAccountWalletsRoute
  '/watchlist': typeof AuthAccountWatchlistRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/_auth/_account': typeof AuthAccountRouteWithChildren
  '/_auth/checkout': typeof AuthCheckoutRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/learn/': typeof LearnIndexRoute
  '/_auth/_account/activity': typeof AuthAccountActivityRoute
  '/_auth/_account/downloads': typeof AuthAccountDownloadsRoute
  '/_auth/_account/offers': typeof AuthAccountOffersRoute
  '/_auth/_account/profile': typeof AuthAccountProfileRoute
  '/_auth/_account/support': typeof AuthAccountSupportRoute
  '/_auth/_account/wallets': typeof AuthAccountWalletsRoute
  '/_auth/_account/watchlist': typeof AuthAccountWatchlistRoute
  '/_auth/orders/$orderId': typeof AuthOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/creators'
    | '/login'
    | '/market'
    | '/register'
    | '/checkout'
    | '/learn/$slug'
    | '/nfts/$nftId'
    | '/learn/'
    | '/activity'
    | '/downloads'
    | '/offers'
    | '/profile'
    | '/support'
    | '/wallets'
    | '/watchlist'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/creators'
    | '/login'
    | '/market'
    | '/register'
    | '/checkout'
    | '/learn/$slug'
    | '/nfts/$nftId'
    | '/learn'
    | '/activity'
    | '/downloads'
    | '/offers'
    | '/profile'
    | '/support'
    | '/wallets'
    | '/watchlist'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cart'
    | '/creators'
    | '/login'
    | '/market'
    | '/register'
    | '/_auth/_account'
    | '/_auth/checkout'
    | '/learn/$slug'
    | '/nfts/$nftId'
    | '/learn/'
    | '/_auth/_account/activity'
    | '/_auth/_account/downloads'
    | '/_auth/_account/offers'
    | '/_auth/_account/profile'
    | '/_auth/_account/support'
    | '/_auth/_account/wallets'
    | '/_auth/_account/watchlist'
    | '/_auth/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  CreatorsRoute: typeof CreatorsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  RegisterRoute: typeof RegisterRoute
  LearnSlugRoute: typeof LearnSlugRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_account': {
      id: '/_auth/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checkout': {
      id: '/_auth/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthCheckoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_account/activity': {
      id: '/_auth/_account/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthAccountActivityRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/downloads': {
      id: '/_auth/_account/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthAccountDownloadsRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/offers': {
      id: '/_auth/_account/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthAccountOffersRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/profile': {
      id: '/_auth/_account/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthAccountProfileRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/support': {
      id: '/_auth/_account/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthAccountSupportRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/wallets': {
      id: '/_auth/_account/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthAccountWalletsRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/_account/watchlist': {
      id: '/_auth/_account/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthAccountWatchlistRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/orders/$orderId': {
      id: '/_auth/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthOrdersOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthAccountRouteChildren {
  AuthAccountActivityRoute: typeof AuthAccountActivityRoute
  AuthAccountDownloadsRoute: typeof AuthAccountDownloadsRoute
  AuthAccountOffersRoute: typeof AuthAccountOffersRoute
  AuthAccountProfileRoute: typeof AuthAccountProfileRoute
  AuthAccountSupportRoute: typeof AuthAccountSupportRoute
  AuthAccountWalletsRoute: typeof AuthAccountWalletsRoute
  AuthAccountWatchlistRoute: typeof AuthAccountWatchlistRoute
}

const AuthAccountRouteChildren: AuthAccountRouteChildren = {
  AuthAccountActivityRoute: AuthAccountActivityRoute,
  AuthAccountDownloadsRoute: AuthAccountDownloadsRoute,
  AuthAccountOffersRoute: AuthAccountOffersRoute,
  AuthAccountProfileRoute: AuthAccountProfileRoute,
  AuthAccountSupportRoute: AuthAccountSupportRoute,
  AuthAccountWalletsRoute: AuthAccountWalletsRoute,
  AuthAccountWatchlistRoute: AuthAccountWatchlistRoute,
}

const AuthAccountRouteWithChildren = AuthAccountRoute._addFileChildren(
  AuthAccountRouteChildren,
)

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRouteWithChildren
  AuthCheckoutRoute: typeof AuthCheckoutRoute
  AuthOrdersOrderIdRoute: typeof AuthOrdersOrderIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRouteWithChildren,
  AuthCheckoutRoute: AuthCheckoutRoute,
  AuthOrdersOrderIdRoute: AuthOrdersOrderIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  CreatorsRoute: CreatorsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  RegisterRoute: RegisterRoute,
  LearnSlugRoute: LearnSlugRoute,
  NftsNftIdRoute: NftsNftIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
